In [1]:
import pandas as pd

In [2]:
!pwd

/Users/prreddy/Documents/EDUeki/Courses/AIDevOps/github/AIDevOps/V1/ML/classification

In [3]:
data = pd.read_csv("../data/loan_data.csv")

In [4]:
data.shape

(4270, 13)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4270 entries, 0 to 4269
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4270 non-null   int64
 1    no_of_dependents          4270 non-null   int64
 2    education                 4270 non-null   str
 3    self_employed             4270 non-null   str
 4    income_annum              4270 non-null   int64
 5    loan_amount               4270 non-null   int64
 6    loan_term                 4270 non-null   int64
 7    credit_score              4266 non-null   float64
 8    residential_assets_value  4270 non-null   int64
 9    commercial_assets_value   4270 non-null   int64
 10   luxury_assets_value       4270 non-null   int64
 11   bank_asset_value          4270 non-null   int64
 12   loan_status               4270 non-null   str
dtypes: float64(1), int64(9), str(3)
memory usage: 433.8 KB

In [6]:
data.head(5)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
4,4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected

In [7]:
data.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4270.000000,4270.000000,4.270000e+03,4.270000e+03,4270.000000,4266.000000,4.270000e+03,4.270000e+03,4.270000e+03,4.270000e+03
mean,2134.500703,2.498829,5.060070e+06,1.513686e+07,10.902576,600.058368,7.472529e+06,4.973044e+06,1.513056e+07,4.978525e+06
std,1232.785938,1.695729,2.807192e+06,9.045051e+06,5.710217,172.405187,6.502877e+06,4.388458e+06,9.106935e+06,3.252009e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1067.250000,1.000000,2.700000e+06,7.700000e+06,6.000000,454.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2134.500000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3201.750000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [8]:
data.columns

Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' credit_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='str')

In [9]:
data[' loan_status']

0        Approved
1        Rejected
2        Rejected
3        Rejected
4        Rejected
          ...
4265     Rejected
4266     Approved
4267     Rejected
4268     Approved
4269     Approved
Name:  loan_status, Length: 4270, dtype: str

In [10]:
data.columns = [i.strip() for i in data.columns]

In [11]:
data.columns

Index(['loan_id', 'no_of_dependents', 'education', 'self_employed',
       'income_annum', 'loan_amount', 'loan_term', 'credit_score',
       'residential_assets_value', 'commercial_assets_value',
       'luxury_assets_value', 'bank_asset_value', 'loan_status'],
      dtype='str')

In [12]:
data.nunique

<bound method DataFrame.nunique of       loan_id  no_of_dependents      education self_employed  income_annum  \
0           1                 2       Graduate            No       9600000
1           2                 0   Not Graduate           Yes       4100000
2           3                 3       Graduate            No       9100000
3           3                 3       Graduate            No       9100000
4           4                 3       Graduate            No       8200000
...       ...               ...            ...           ...           ...
4265     4265                 5       Graduate           Yes       1000000
4266     4266                 0   Not Graduate           Yes       3300000
4267     4267                 2   Not Graduate            No       6500000
4268     4268                 1   Not Graduate            No       4100000
4269     4269                 1       Graduate            No       9200000

      loan_amount  loan_term  credit_score  residential_assets_value  \
0        29900000         12         778.0                   2400000
1        12200000          8         417.0                   2700000
2        29700000         20         506.0                   7100000
3        29700000         20         506.0                   7100000
4        30700000          8         467.0                  18200000
...           ...        ...           ...                       ...
4265      2300000         12         317.0                   2800000
4266     11300000         20         559.0                   4200000
4267     23900000         18         457.0                   1200000
4268     12800000          8         780.0                   8200000
4269     29700000         10         607.0                  17800000

      commercial_assets_value  luxury_assets_value  bank_asset_value  \
0                    17600000             22700000           8000000
1                     2200000              8800000           3300000
2                     4500000             33300000          12800000
3                     4500000             33300000          12800000
4                     3300000             23300000           7900000
...                       ...                  ...               ...
4265                   500000              3300000            800000
4266                  2900000             11000000           1900000
4267                 12400000             18100000           7300000
4268                   700000             14100000           5800000
4269                 11800000             35700000          12000000

     loan_status
0       Approved
1       Rejected
2       Rejected
3       Rejected
4       Rejected
...          ...
4265    Rejected
4266    Approved
4267    Rejected
4268    Approved
4269    Approved

[4270 rows x 13 columns]>

In [13]:
data.nunique()

loan_id                     4269
no_of_dependents               6
education                      2
self_employed                  2
income_annum                  98
loan_amount                  378
loan_term                     10
credit_score                 601
residential_assets_value     278
commercial_assets_value      188
luxury_assets_value          379
bank_asset_value             146
loan_status                    2
dtype: int64

In [14]:
data.drop(columns=['loan_id'], inplace=True)

In [15]:
data.shape

(4270, 12)

In [16]:
data.head(4)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected

In [17]:
data.duplicated().sum()

np.int64(1)

In [18]:
data.drop_duplicates(keep='first',inplace=True, ignore_index=False)

In [19]:
data.head(4)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected
4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected

In [20]:
data['self_employed'].unique()

<StringArray>
[' No', ' Yes']
Length: 2, dtype: str

In [21]:
data['education'] = data['education'].str.strip()
data['self_employed'] = data['self_employed'].str.strip()
data['loan_status'] = data['loan_status'].str.strip()

In [22]:
data['self_employed'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [23]:
data.isnull().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
credit_score                4
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [24]:
data['credit_score'] = data['credit_score'].fillna(data['credit_score'].mean())

In [25]:
data.isnull().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
credit_score                0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [26]:
data['total_assets'] = data['residential_assets_value'] + data['commercial_assets_value'] + data['luxury_assets_value'] + data['bank_asset_value']

In [27]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,total_assets
0,2,Graduate,No,9600000,29900000,12,778.0,2400000,17600000,22700000,8000000,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417.0,2700000,2200000,8800000,3300000,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506.0,7100000,4500000,33300000,12800000,Rejected,57700000
4,3,Graduate,No,8200000,30700000,8,467.0,18200000,3300000,23300000,7900000,Rejected,52700000
5,5,Not Graduate,Yes,9800000,24200000,20,382.0,12400000,8200000,29400000,5000000,Rejected,55000000

In [28]:
data.drop(columns=['residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'], inplace=True)

In [29]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_assets
0,2,Graduate,No,9600000,29900000,12,778.0,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417.0,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506.0,Rejected,57700000
4,3,Graduate,No,8200000,30700000,8,467.0,Rejected,52700000
5,5,Not Graduate,Yes,9800000,24200000,20,382.0,Rejected,55000000

In [30]:
data.shape

(4269, 9)

In [31]:
education_map = {'Graduate': 1, 'Not Graduate': 0}

In [32]:
data['education'] = data['education'].map(education_map)

In [33]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_assets
0,2,1,No,9600000,29900000,12,778.0,Approved,50700000
1,0,0,Yes,4100000,12200000,8,417.0,Rejected,17000000
2,3,1,No,9100000,29700000,20,506.0,Rejected,57700000
4,3,1,No,8200000,30700000,8,467.0,Rejected,52700000
5,5,0,Yes,9800000,24200000,20,382.0,Rejected,55000000

In [34]:
self_employed_map = {'No': 1, 'Yes': 0}
data['self_employed'] = data['self_employed'].map(self_employed_map)

In [35]:
loan_status_map = {'Approved': 1, 'Rejected': 0}
data['loan_status'] = data['loan_status'].map(loan_status_map)

In [36]:
data.head(5)

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_assets
0,2,1,1,9600000,29900000,12,778.0,1,50700000
1,0,0,0,4100000,12200000,8,417.0,0,17000000
2,3,1,1,9100000,29700000,20,506.0,0,57700000
4,3,1,1,8200000,30700000,8,467.0,0,52700000
5,5,0,0,9800000,24200000,20,382.0,0,55000000

In [37]:
!python3 -m pip install numpy

Requirement already satisfied: numpy in /Users/prreddy/Documents/EDUeki/Courses/AIDevOps/code/ML/.venv/lib/python3.11/site-packages (2.4.6)

[notice] A new release of pip is available: 25.3 -> 26.2.2
[notice] To update, run: pip install --upgrade pip

In [38]:
import numpy as np

In [39]:
data['income_annum'] = np.log(data['income_annum'])

In [40]:
data.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_assets
0,2,1,1,16.077274,29900000,12,778.0,1,50700000
1,0,0,0,15.226498,12200000,8,417.0,0,17000000
2,3,1,1,16.023785,29700000,20,506.0,0,57700000
4,3,1,1,15.919645,30700000,8,467.0,0,52700000
5,5,0,0,16.097893,24200000,20,382.0,0,55000000

In [41]:
data['loan_amount'] = np.log(data['loan_amount'])
data['total_assets'] = np.log(data['total_assets'])

In [42]:
data.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,loan_status,total_assets
0,2,1,1,16.077274,17.213369,12,778.0,1,17.741436
1,0,0,0,15.226498,16.316947,8,417.0,0,16.648724
2,3,1,1,16.023785,17.206658,20,506.0,0,17.870768
4,3,1,1,15.919645,17.239773,8,467.0,0,17.780126
5,5,0,0,16.097893,17.001863,20,382.0,0,17.822844

In [43]:
X = data.drop(columns=['loan_status'])

In [44]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,credit_score,total_assets
0,2,1,1,16.077274,17.213369,12,778.0,17.741436
1,0,0,0,15.226498,16.316947,8,417.0,16.648724
2,3,1,1,16.023785,17.206658,20,506.0,17.870768
4,3,1,1,15.919645,17.239773,8,467.0,17.780126
5,5,0,0,16.097893,17.001863,20,382.0,17.822844

In [45]:
Y = data['loan_status']

In [46]:
Y.head()

0    1
1    0
2    0
4    0
5    0
Name: loan_status, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

In [64]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=54, stratify=Y)

In [72]:
from sklearn.tree import DecisionTreeClassifier

In [74]:
model = DecisionTreeClassifier()

In [75]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [81]:
predict_prob = model.predict_proba(x_test)

In [83]:
predict_prob[:5].round(3)

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [76]:
predictions = model.predict(x_test)

In [80]:
predictions

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1])

In [77]:
from sklearn.metrics import accuracy_score

In [78]:
score = accuracy_score(y_test, predictions)

In [79]:
score

0.9836065573770492

In [84]:
from sklearn.metrics import confusion_matrix

In [85]:
cm = confusion_matrix(y_test, predictions)

In [86]:
cm

array([[158,   3],
       [  4, 262]])

In [87]:
pd.DataFrame(cm, index=['actually Rejected', 'actually Approved'], columns=['predicted Rejected', 'predicted Approved'])

                   predicted Rejected  predicted Approved
actually Rejected                 158                   3
actually Approved                   4                 262